server:
  # ????????? ???? 8083, ????? ?? ?? ???????????? ? ??????? ????????? (A ? B)
  port: 8083

spring:
  datasource:
    # URL ???????????. 'localhost:5432' ? ?????? ??? ???? ?????? ? ??????,
    # ? ?????? ?? ????????? ?? IDEA. 'service_c_db' ? ??? ???? ?? docker-compose.
    url: jdbc:postgresql://localhost:5432/service_c_db
    username: postgres
    password: password

  jpa:
    hibernate:
      # 'none' ????????, ??? Hibernate ?? ????? ??? ????????? ???????.
      # ?? ???????? ??? Liquibase, ????? ??? ???? ??? ?????????.
      ddl-auto: none
    # ???????? ??????????? SQL-???????? ? ???????, ????? ??????, ??? ????? ? ????.
    show-sql: true

  kafka:
    # ????? ??????? ????????? ??? ????? ????????.
    bootstrap-servers: localhost:9092
    producer:
      # ????????? ????, ??? ?????????? Java-??????? ? ????? ??? ???????? ?? ????.
      # ???? ?????????? ??????? ?????? (String).
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer